cluster.name: ${CLUSTER_NAME}
node.name: ${NODE_NAME}
network.host: 0.0.0.0
http.port: 9200

discovery.type: single-node

bootstrap.memory_lock: true

xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true

logger.level: info

http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: X-Requested-With,Content-Type,Content-Length,Authorization
http.cors.allow-credentials: true

action.auto_create_index: true

cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%