server.name: kibana
server.host: "0.0.0.0"
server.port: 5601

elasticsearch.hosts: ["http://elasticsearch:9200"]

i18n.locale: "en"

telemetry.enabled: false

monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

logging:
  appenders:
    console:
      type: console
      layout:
        type: json
  root:
    appenders:
      - console
    level: info