config.reload.automatic: true
config.reload.interval: 3s
http.host: 0.0.0.0
log.level: info
monitoring.enabled: false
path.config: /usr/share/logstash/pipeline
queue.max_bytes: 1gb
queue.type: memory
xpack.management.enabled: ${XPACK_MANAGEMENT_ENABLED}
xpack.monitoring.enabled: ${XPACK_MONITORING_ENABLED}
